### ISSUE TITLE
"Close e" has non-standard fofm

### ISSUE THREAD

**Issue by soosistvangithub** [glaza/cserkesz-rovasiras#1]
@glaza The "close e" has wrong, non-standard form. The Unicode standard is downloadable from:
https://unicode.org/charts/PDF/U10C80.pdf
Please, follow the standard!

**Comment by glaza** [comment]
Szia István, ez a projekt egy ötlet volt hogy a rendes latin betűket át rajzolom cserkész róvásírásba.
Azóta, írtam Sztupák Zsoltnak (https://oldhungarian.eu/index_en.html) és ő lebeszélt róla.
Szóval, most arra gondolok hogy egyszerűen át rajzolnám a betűket a helyes Unicode pozicióban. Lehet hogy majd Zsolt honlapjának hozájárulok hogy cserkész és székely róvásírástból lehessen választani.
De ez a projekt egy kicsit le maradt mert egy munkaterv honlapot készítek az őrsvezetőimnek 😄

**Comment by soosistvangithub** [comment]
Bocs, az Androidos Andropen office program vágott át. Telepítettem és beállítottam erre a betűkészletre, a rovás billentyűzetre reagálva kiválasztott egy hibás rovás betűkészletet hozzá.
Az viszont tényleg nagy hiba, ha a latin területre tetted át a rovást. Etikátlan. Van már rovás billentyűzet a https://keyman.com projekten belül Windowsra is. Csak a projektoldal keresőmezőjébe kell begépelni  az "Old Hungarian" szöveget. Microsoft Office-szal ne is próbálkozz, LibreOffice-t használd helyette. Két beállítás kell hozzá, és működik jobbról balra a szöveg. Már ha érdekel...

**Comment by soosistvangithub** [comment]
@glaza Addig is lezárom ezt a hibajegyet.
